config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :authors
  root "authors#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :author_books
  has_many :books, through: :author_books, dependent: :destroy

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
  belongs_to :author
  belongs_to :book
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :author_books
  has_many :authors, through: :author_books, dependent: :destroy

  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(params.require(:author).permit(:first_name, :last_name, :dob, :bookid, book_ids: []))

    respond_to do |format|
      if @author.save
        format.html { redirect_to author_url(@author), notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(params.require(:author).permit(:first_name, :last_name, :dob, :bookid, book_ids: []))
        format.html { redirect_to author_url(@author), notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:first_name, :last_name, :dob, :bookid, book_ids: [])
    end

    def get_books
      @all_books = Book.all
      @author_book = @author.authorbooks.build
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(params.require(:book).permit(:title,:description, author_ids: []))

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(params.require(:book).permit(:title,:description, author_ids: []))
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :description, author_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
<% if author.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

  <ul>
    <% author.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="card">
  <br/>
  <h5 class="card-header">Author</h5>
  <div class="card-body">
    <h5 class="card-title">First name:</h5>
    <p class="card-text"><%= form.text_field :first_name %></p>
    <h5 class="card-title">Last name:</h5>
    <p class="card-text"><%= form.text_field :last_name %></p>
    <h5 class="card-title">Date of birth:</h5>
    <p class="card-text"><%= form.date_field :dob %></p>
    <h5 class="card-title">Book id:</h5>
      <%= form.collection_select(:book_ids, Book.all, :id, :title,{:"data-style" => "chosen-select", :"data-size" => "5"}, {class: "selectpicker", title: "Choose Book(s)", multiple: true})%>




    <%= form.submit :class=>"btn btn-primary"%>
  </div>
</div>
<% end %>

<script>
  $('select').selectpicker();



</script>

app/views/authors/edit.html.erb
<br/>
<h1>Edit Author</h1>
<br/>
<%= render 'form', author: @author %>
<br/>
<%= link_to 'Show', @author , :class=>"btn btn-secondary"%>
<%= link_to 'Back', authors_path , :class=>"btn btn-dark"%>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Author name</th>
      <th>Dob</th>
      <th>Book/s of the authors</th>
      <th>Delete author</th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= link_to author.first_name + " " + author.last_name, author %></td>
        <td><%= author.dob %></td>
        <td><%= author.book_ids %></td>
        <td><%= link_to 'Delete', author, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path, :class=>"btn btn-primary" %>

app/views/authors/new.html.erb
<br/>
<h1>New Author</h1>
<br/>
<%= render 'form', author: @author %>
<br/>

<%= link_to 'Back', authors_path, :class=>"btn btn-secondary" %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>




<div class="jumbotron">
  <h1 class="display-4">Author Name:
  <p class="lead"><%= @author.first_name + " " + @author.last_name%></p></h1>
  <hr class="my-4">
  <p>Date of birth:
  <%= @author.dob %></p>
  <%= link_to 'Edit', edit_author_path(@author) ,:class=>"btn btn-secondary"%>
  <%= link_to 'Back', authors_path ,:class=>"btn btn-dark" %>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card">
    <br/>
    <h5 class="card-header">Book</h5>
    <div class="card-body">
      <h5 class="card-title">Title:</h5>
      <p class="card-text"><%= form.text_field :title %></p>
      <h5 class="card-title">Description:</h5>
      <p class="card-text"><%= form.text_field :description %></p>
      <h5 class="card-title">Author id:</h5>
      <%# <!-- <p class="card-text"><%= form.collection_check_boxes :author_ids, Author.all, :id, :full_name, { hide_label: true } %>
        <%= form.collection_select(:author_ids, Author.all, :id, :full_name,{:"data-style" => "chosen-select", :"data-size" => "5"}, {class: "selectpicker", title: "Choose Author(s)", multiple: true})%>


<%#
        <%= f.select :account_id,
      options_for_select(@entities.collect{ |e|
        [e.entity, e.entity]
      }, 1),
      { include_blank: '-Select-' },
      { multiple: true, size: [@entities.size, 10].max }
      { id: 'my_entity'}
%>


      <%= form.submit :class=>"btn btn-primary"%>
    </div>
  </div>
<% end %>

<script>
  $('select').selectpicker();

</script>

app/views/books/edit.html.erb
<br/>
<h1>Editing Book</h1>
<br/>
<%= render 'form', book: @book %>

<br/>
<%= link_to 'Show', @book ,:class=>"btn btn-secondary"%> 
<%= link_to 'Back', books_path, :class=>"btn btn-dark" %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Author/s of the books</th>
      <th>Delete book</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.title, book %></td>
        <td><%= book.description %></td>
        <td><%= book.author_ids %></td>
        <td><%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path, :class=>"btn btn-primary" %>

app/views/books/new.html.erb
<br/>
<h1>New Book</h1>
<br/>
<%= render 'form', book: @book %>
<br/>
<%= link_to 'Back', books_path, :class=>"btn btn-secondary" %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>



<div class="jumbotron">
  <h1 class="display-4">Book Title:
  <p class="lead"><%= @book.title %></p></h1>
  <hr class="my-4">
  <p>Description:
  <%= @book.description %></p>
  <%= link_to 'Edit', edit_book_path(@book) ,:class=>"btn btn-secondary"%>
  <%= link_to 'Back', books_path ,:class=>"btn btn-dark" %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Authors", authors_path ,:class=>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Books", books_path ,:class=>"nav-link" %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>LibraryApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <br/>
      <%= render "layouts/header"%>
    <%= yield %>
    </div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>